config/routes.rb
DignityBet::Application.routes.draw do  
  resources :bets

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  match 'bet/pick_challenger', to: 'bets#pick_challenger', as: 'pick_challenger'
  match 'bet/:id/accept', to: 'bets#accept', as: 'accept_bet'
  
  get 'bet/:id/determine_result', to: 'bets#determine_result', as: 'determine_result'
  get 'bet/:id/set_result', to: 'bets#set_result', as: 'set_result'

  match 'history', to: 'bets#history', as: 'history'
  
  root to: 'sessions#login'
  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  attr_accessible :challenge, :challenger_id, :lose_status, :owner_id, :status, :win_status, :owner_says, :challenger_says
  
  belongs_to :owner, :class_name => 'User', :foreign_key => :owner_id
  belongs_to :challenger, :class_name => 'User', :foreign_key => :challenger_id
  
  def role(user)
    if self.owner.id == user.id
      return "owner"
    elsif self.challenger.id == user.id
      return "challenger"
    else 
      return false
    end  
  end
  
  def set_result(user, determination)
    if self.role(user) == "owner"
      self.owner_says = determination
      self.save
    elsif self.role(user) == "challenger"
      self.challenger_says = determination
      self.save
    else
      return false
    end  
  end
  
  def decided?
    if owner_says == "draw" && challenger_says == "draw"
      return true
    elsif (owner_says == "won" && challenger_says == "lost") || (owner_says == "lost" && challenger_says == "won")
      return true
    else
      return false
    end
  end
  
  def winner
    if self.owner_says == "won" && self.challenger_says == "lost"
      return self.owner
    elsif self.owner_says == "lost" && self.challenger_says == "won"
      return self.challenger
    elsif self.owner_says == "draw" && self.challenger_says == "draw"
      return "draw"
    elsif self.owner_says == nil || self.challenger_says == nil
      return "undecided"
    else
      return "disputed"
    end
  end
  
  def other_guy(me)
    if owner == me
      return challenger
    else
      return owner
    end
  end
  
  def result(player)
    if winner == player
      return 'won'
    elsif winner == other_guy(player)
      return 'lost'
    elsif winner == "draw" 
      return 'drew'
    else
      return winner
    end
  end
      
  def post_loser_status
    if decided? && winner != "draw"
      puts other_guy(winner).oauth_token
      losers_facebook = Koala::Facebook::API.new(other_guy(winner).oauth_token)

      if winner = owner
        losers_facebook.put_wall_post(win_status)
      else
        losers_facebook.put_wall_post(lose_status)
      end
    else 
      return false
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  
  has_many :bets, :foreign_key => 'owner_id'
  has_many :challenges, :foreign_key => 'challenger_id'

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  
  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end
  
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # GET /bets
  # GET /bets.json
  def index
    
    @bets = Bet.where("challenger_id = ? or owner_id = ?", current_user.id, current_user.id)
    
    @bet_requests = []
    @active_bets = []
    @bets_won = []
    @awaiting_accept = []
    
    @bets.each do |bet|
        @bet_requests << bet if (bet.status=='pending' && bet.owner != current_user)
        @active_bets << bet if (bet.status=='active')
        @awaiting_accept << bet if (bet.status == 'pending' && bet.owner == current_user)
        @bets_won << bet if (bet.status=="won" and bet.owner == current_user)
        @bets_won << bet if (bet.status=="lost" and bet.owner != current_user)
    end 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bets }
    end
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
    @bet = Bet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/new
  # GET /bets/new.json
  def new
    @bet = Bet.new
    @challenger = User.find_by_id(params[:challenger_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/1/edit
  def edit
    @bet = Bet.find(params[:id])
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(params[:bet])

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render json: @bet, status: :created, location: @bet }
      else
        format.html { render action: "new" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bets/1
  # PUT /bets/1.json
  def update
    @bet = Bet.find(params[:id])

    respond_to do |format|
      if @bet.update_attributes(params[:bet])
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy

    respond_to do |format|
      format.html { redirect_to bets_url }
      format.json { head :no_content }
    end
  end
  
  def pick_challenger
    
    begin
      friend_ids = current_user.facebook.get_connections("me","friends").map{ |friend| (friend["id"])}
    rescue
      redirect_to "/signout"
    else
      @friends_with_app = User.find_all_by_uid(friend_ids)
    end
  
  end
  
  def accept
    @bet = Bet.find(params[:id])
  end
  
  def determine_result
    @bet = Bet.find(params[:id])
    @role = @bet.role(current_user)
    
  end
  
  def set_result
    @bet = Bet.find(params[:id])
    @bet.set_result(current_user, params[:determination])
    
    @tense_change = {"draw" => "draw", "won" => "win", "lost" => "lose"}
    if @bet.decided? 
      @bet.post_loser_status
      @bet.status = @bet.result(@bet.owner)
      @bet.save
    end
    
  end
  
  def history
    @bets = Bet.where("challenger_id = ? or owner_id = ? and status != ?", current_user.id, current_user.id, "active")
    
    @bets_drawn = []
    @bets_won = []
    @bets_lost = []
    
    @bets.each do |bet|
        @bets_drawn << bet if (bet.status=='drew')
        @bets_won << bet if (bet.winner == current_user)
        @bets_lost << bet if (bet.winner == bet.other_guy(current_user))
    end 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bets }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def login
    if current_user.present? 
      redirect_to bets_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div>
    <div class="input-group">
      <div class="input-row">
        <%= f.label :challenge %>
        <%= f.text_field :challenge, :placeholder => "What's the bet?" %>
      </div>
      <div class="input-row">
        <%= f.label :win_status %>
        <%= f.text_field :win_status, :placeholder => "Embarrassing status" %>
      </div>
    </div>
      
      <%= f.hidden_field(:status, value: "pending") %>
      <%= f.hidden_field(:owner_id, value: current_user.id) %>
      <%= f.hidden_field(:challenger_id, value: @challenger.id) %>
      <%= f.submit"Lay down the challenge!", :class => "button-block button-negative" %>
  </div>
<% end %>

app/views/bets/accept.html.erb
<header class="bar-title">
  <%= link_to 'Cancel', bets_path, "data-transition" => "slide-out", class: 'button-prev' %>
  <h1 class="title">Dignity Bet</h1>
  <%= link_to pick_challenger_path, "data-transition" => "slide-in", onclick:"alert('wassup')", class: 'button' do %>
    <i class='icon-plus' style="font-size:15px"></i>
  <% end  %>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>

         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>

<div class="content">
  <div class="content-padded">
    <h2>Accept bet with <%= @bet.owner.name %></h2>
    <p><%= @bet.challenge %></p>
    <br />
    <%= form_for(@bet) do |f| %>
      <div class="input-group">
        <div class="input-row">
          <%= f.label :status %>
          <%= f.text_field :lose_status, :placeholder => "Losing Status for #{@bet.owner.name}" %>
        </div>
      </div>
      <%= f.hidden_field :status, value: "active" %>
      <%= f.submit "Accept Bet", class: "button-block button-main" %>
    <% end %>

  </div>
</div>

app/views/bets/determine_result.html.erb
<header class="bar-title">
  <%= link_to 'Back', @bet, "data-transition" => "slide-out", class: 'button-prev' %>
  <h1 class="title bold">DIGNITY BET</h1>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>

<div class="content">
  <div class="content-padded">

<%= link_to "I Won", set_result_path(:id => @bet.id, :role => @role, :determination => "won"), class: "button-block button-positive" %>
<%= link_to "I Lost", set_result_path(:id => @bet.id, :role => @role, :determination => "lost"), class: "button-block button-negative" %>
<%= link_to "It's a draw", set_result_path(:id => @bet.id, :role => @role, :determination => "draw"), class: "button-block" %>

</div>
</div>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/history.html.erb
<header class="bar-title">
  <%= link_to history_path, class: 'button', style: "border:none;" do %>
    <i class='icon-refresh' style="font-size:15px"></i>
  <% end  %>
  <h1 class="title bold">Past Bets</h1>
  <%= link_to pick_challenger_path, "data-transition" => "slide-in", class: 'button' do %>
    <i class='icon-plus' style="font-size:15px"></i>
  <% end  %>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item">
       <%= link_to bets_path, "data-transition" => "slide-out" do %>
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       <% end %>
     </li>
     <li class="tab-item active">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>

<div class="content">

<ul class='list'>

<li class="list-divider">Won <span class="count"><%= @bets_won.count %></span></li>
<% @bets_won.each do |bet| %>  
  <li>
    <%= link_to bet,  "data-transition" => "slide-in" do %>
      <h2 ><%= bet.challenger.name %></h2>
      <p><%= bet.challenge %></p>
      <span class="chevron"></span>
    <% end %>
  </li>
<% end %>  

<li class="list-divider">Lost <span class="count"><%= @bets_lost.count %></span></li>
<% @bets_lost.each do |bet| %>  
  <li>
    <%= link_to bet,  "data-transition" => "slide-in" do %>
    <h2><%= bet.challenger.name %></h2>
    <p><%= bet.challenge %></p>
    <span class="chevron"></span>
    <% end %>
  </li>
<% end %>

<li class="list-divider">Drawn <span class="count"><%= @bets_drawn.count %></span></li>
<% @bets_drawn.each do |bet| %>  
  <li>
    <%= link_to bet,  "data-transition" => "slide-in" do %>
    <h2><%= bet.challenger.name %></h2>
    <p><%= bet.challenge %></p>
    <span class="chevron"></span>
    <% end %>
  </li>
<% end %>
</ul>

  
</div>

app/views/bets/index.html.erb
<header class="bar-title">
  <%= link_to bets_path, class: 'button', style: "border:none;" do %>
    <i class='icon-refresh' style="font-size:15px"></i>
  <% end  %>
  <h1 class="title bold">Current Bets</h1>
  <%= link_to pick_challenger_path, "data-transition" => "slide-in", class: 'button' do %>
    <i class='icon-plus' style="font-size:15px"></i>
  <% end  %>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <%= link_to history_path, "data-transition" => "slide-in" do %>
         <i class="icon-time" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Past Bets</div>
       <% end %>
     </li>
   </ul>
 </nav>

<div class="content">

<ul class='list'>

<li class="list-divider">Challenge requests <span class="count" style="background-color: red;"><%= @bet_requests.count %></span></li>
<% @bet_requests.each do |bet| %>
  <li>
    <%= link_to accept_bet_path(bet),  "data-transition" => "slide-in" do %>
      <h2><%= bet.challenger.name %></h2>
      <p><%= bet.challenge %></p>
      <span class="chevron"></span>
    <% end %>
  </li>
<% end %>

<li class="list-divider">Pending Challenger Accept<span class="count" style="background-color: blue;"><%= @awaiting_accept.count %></span></li>
<% @awaiting_accept.each do |bet| %>
  <li>
      <h2><%= bet.challenger.name %></h2>
      <p><%= bet.challenge %></p>
  </li>
<% end %>

<li class="list-divider">Active Bets  <span class="count"><%= @active_bets.count %></span></li>
<% @active_bets.each do |bet| %>  
  <li>
    <%= link_to bet,  "data-transition" => "slide-in" do %>
      <h2 ><%= bet.challenger.name %></h2>
      <p><%= bet.challenge %></p>
      <span class="chevron"></span>
    <% end %>
  </li>
<% end %>  
</ul>

  
</div>

app/views/bets/new.html.erb
<header class="bar-title">
  <%= link_to 'Back', pick_challenger_path, "data-transition" => "slide-out", class: 'button-prev' %>
  <h1 class="title">Create Bet</h1>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>

         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>

<div class="content">
  <div class="content-padded">
    <h2>Showdown with <%= @challenger.name %></h2>
    <br/>

    <%= render 'form' %>

  </div>
</div>

app/views/bets/pick_challenger.html.erb
<header class="bar-title">
  <%= link_to 'Back', bets_path, "data-transition" => "slide-out", class: 'button-prev' %>
  <h1 class="title">Friends with Dignity Bet</h1>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>

         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>


<div class="content">
  <div class="content-padded">



<ul class="list">
  <% @friends_with_app.each do |friend| %>
    <li>
    <%= link_to new_bet_path(:challenger_id=>friend.id), "data-transition" => "slide-in"  do %>
    <%= image_tag "http://graph.facebook.com/#{friend.uid}/picture?type=small", width: "50" %> 
     <div class="friend-text"><%= friend.name %></div>
     <span class="chevron"></span></li>
    <% end %>
  <% end %>
</ul>

</div>
</div>

app/views/bets/set_result.html.erb
<header class="bar-title">
  <%= link_to 'Back', @bet, "data-transition" => "slide-out", class: 'button-prev' %>
  
  <h1 class="title">DIGNITY BET</h1>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>

         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>

<div class="content">
  <div class="content-padded">
    
  <% if @bet.decided? %>
    <% if @bet.winner == current_user %>
      Winner!
    
      <%= image_tag "http://graph.facebook.com/#{@bet.winner.uid}/picture?type=small", width: "50" %> <%= @bet.winner.name %>
      Def
      <%= image_tag "http://graph.facebook.com/#{@bet.other_guy(@bet.winner).uid}/picture?type=small", width: "50" %><%=   @bet.other_guy(@bet.winner).name %>
    
    <% elsif @bet.winner == 'draw' %>
      <div class='logo'><i class='icon-heart'></i>
          <h1 class='logo-text'>It's a Draw!</h1>
      </div>
      <div class='sublogo-text'>
        I guess you and <%= @bet.other_guy(current_user).name %> can still be friends
      </div>
    <% elsif @bet.winner == @bet.other_guy(current_user) %>
      You Lost!
    
      <%= image_tag "http://graph.facebook.com/#{@bet.winner.uid}/picture?type=small", width: "50" %> <%= @bet.winner.name %>
      Def
      <%= image_tag "http://graph.facebook.com/#{@bet.other_guy(@bet.winner).uid}/picture?type=small", width: "50" %><%= @bet.other_guy(@bet.winner).name %>
    
    <% end %>
  

  
  <% else %>

    <% if @bet.winner == 'disputed' %>
      <div class='logo'><i class='icon-exclamation-sign'></i>
        <h1 class='logo-text'>Dispute!</h1>
      </div>
      <div class='sublogo-text'>
        <%= @bet.other_guy(current_user).name %> says you didn't <%= @tense_change[params[:determination]] %>
      </div>
    
      <% elsif @bet.winner == 'undecided' %>
      <div class='logo'><i class='icon-time'></i>
        <h1 class='logo-text'>Undecided</h1>
      </div>
      <div class='sublogo-text'>
        Waiting on <%= @bet.other_guy(current_user).name %>
      </div>
      <% end %>
    
  <% end %>

  </div>
  </div>

app/views/bets/show.html.erb
<header class="bar-title">
  <%= link_to 'Back', bets_path, "data-transition" => "slide-out", class: 'button-prev' %>
  <h1 class="title">Challenge</h1>
</header>

<nav class="bar-tab">
   <ul class="tab-inner">
     <li class="tab-item active">
       <a href="">
         <i class="icon-pushpin" style='color:white; font-size: 30px;'></i>
         <div class="tab-label">Live Bets</div>
       </a>
     </li>
     <li class="tab-item">
       <a href="">
         <i class="icon-time" style='color:white; font-size: 30px;'></i>

         <div class="tab-label">Past Bets</div>
       </a>
     </li>

     </li>
   </ul>
 </nav>

<div class="content">
  <div class="content-padded">
    
<p id="notice"><%= notice %></p>

<table class="head-to-head">
  <tr>
    <td class="head-to-head">
      <div><%= image_tag "http://graph.facebook.com/#{@bet.owner.uid}/picture?type=large", width: 100 %></div>
    </td>
    <td>
      <h1><i class="icon-bolt"></i></h1>
    </td>
    <td class="head-to-head">
      <div><%= image_tag "http://graph.facebook.com/#{@bet.challenger.uid}/picture?type=large", width: 100 %></div>
    </td>
  </tr>
  <tr>
    <td>
      <h3><%= @bet.owner.name %></h3>
    </td>
    <td>
    </td>
    <td>
      <h3><%= @bet.challenger.name %></h3>
    </td>
</table>

<h3 class="logo-text"><%= @bet.challenge %></h3>

<% case @bet.status %>
<% when "drew" %>
  <h3 class="result-text">It's a Draw!</h3>
<% when "active" %>
  <!-- <h3 class="result-text" style="color:green;">Active</h3> -->
<% when "lost","won" %>
  <% if @bet.winner == current_user %>
    <h3 class="result-text">You won!</h3>
  <% else %>
    <h3 class="result-text">You lost :-(</h3>
  <% end %>
<% end %>


<%= link_to 'Set Result', determine_result_path(id: @bet.id), "data-transition" => "slide-in", class: "button-block button-main" if (@bet.status=="active") %>




</div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dignity Bet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <!-- Sets initial viewport load and disables zooming  -->
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width;">

  <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <!-- Set Apple icons for when prototype is saved to home screen -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/app_icons/icon-114x114.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/app_icons/icon-72x72.png">
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/app_icons/icon-57x57.png">

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,800,300,700' rel='stylesheet' type='text/css'>
  
  <script>
    window.config = "<%= root_url %> <%= ENV['APP_ID'] %>"
  </script>
  
</head>
  
<body>

<%= yield %>
</body>
</html>